### PR TITLE
Add simple SOS-OFI build script

### PR DESCRIPTION
**Pull request by jdinan**
Signed-off-by: James Dinan <james.dinan@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
@hppritcha Will this help with Jenkins?

**Comment by jdinan** [comment]
@kseager @davidozog Any objections?  This adds a sample build script to the scripts directory, so it's fairly low risk.

**Comment by davidozog** [comment]
I think it's great.  I just tested it successfully.  Also, this way our scripts directory isn't quite as lonely.

**Comment by jdinan** [comment]
Thanks!  It should also be useful in cases where someone wants a quick SHMEM testing environment.  I'm hoping to use this in the OpenSHMEM spec CI testing script.

**Pull request merged**
