### PR TITLE
Add memcpy "transport"

### PR DESCRIPTION
**Pull request by jdinan**
Replaces #480

### CODE REVIEW

**Comment by davidozog** [comment]
If the user passes --with-xpmem (or --with-cma) as well as --enable-memcpy, then this will (kinda quietly) drop the memcpy, right?  Is that ok?  Perhaps a warning would be good during configure, but it's no big deal.  Otherwise looks good.

**Comment by ireed** [comment]
If xpmem or cma is enabled then the new code should never be reached.

**Comment by davidozog** [comment]
Right but if both xpmem (or cma) _and_ memcpy are enabled, then the new code is not reached either.  I'm just saying a warning in configure might be good so users know that xpmem/cma are prioritized if they accidentally request memcpy as well.

**Comment by ireed** [comment]
.... well, unless you use compile tricks such as setting -DUSE_SELF_OPTIMIZATION.

**Comment by davidozog** [comment]
On second thought, we could just print "transport_memcpy = yes" at the end of configure if any of the the shared memory transports are enabled, but only `USE_MEMCPY` if it alone is enabled (Jim's idea).  I'll push the change now and you guys can review.

**Pull request merged**
