### PR TITLE
Add missing comma for shmem_put_signal to shmem.h4

### LINKED ISSUE #1006: shmem_put_signal() generic selection failing on example code
i'm getting C11 selection errors when trying to compile Example 27 from the 1.5 spec, which uses shmem_put_signal().

configure:   $ ./configure --prefix=/opt/tools/modules/sandia-openshmem --without-ofi --with-ucx --with-pmi=/opt/scyld/slurm

When compiling the example code I get the following error:
```
/opt/tools/modules/sandia-openshmem/include/shmem.h:5819:13: error: expected ')' before 'default'
 5819 |             default: shmem_ctx_c11_generic_selection_failed \
      |             ^~~~~~~
signal_test.c:24:5: note: in expansion of macro 'shmem_put_signal'
   24 |     shmem_put_signal(data, message, size, &sig_addr, 1, SHMEM_SIGNAL_SET, pe);
```

This happens when compiling SOS with gcc-10.2.0. Similar results with Clang 11.0 and AOCC (Clang 12.0).
example code attached.

brian.

[signal_test.txt](https://github.com/Sandia-OpenSHMEM/SOS/files/6832808/signal_test.txt)

### PR DESCRIPTION
**Pull request by davidozog**
I'm hoping this fixes #1006 

Signed-off-by: David Ozog <david.m.ozog@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
Good catch! Looks like the same bug is also in `shmem_put_signal_nbi`.

**Comment by davidozog** [comment]
Oh, that's also a good catch.  Thanks!

I plan to add the example 27 from the spec to this PR (under test/spec-examples).  Looks like it was missed.

**Comment by wrrobin** [comment]
The spec example test is almost identical to this one: https://github.com/Sandia-OpenSHMEM/SOS/blob/master/test/unit/put_signal.c
I remember I did not add the spec example because we have a similar one.

**Comment by davidozog** [comment]
It looks like our Travis credits are now exhausted, which happened more quickly than I expected.

I'll focus on porting our Travis CI to GitHub actions, but I'd say this PR can probably be reviewed/merged.  I created an issue to add C11 testing coverage for `shmem_put_signal` and `shmem_put_signal_nbi` #1011 targeting SOS release v1.5.1.

**Review by wrrobin — APPROVED** [review]

**Pull request merged**
