### PR TITLE
Changed mt_a2a.c such that the test works.

### PR DESCRIPTION
**Pull request by AMcKinley15**
File was missing a pthread barrier and was causing unspecified execution.

Signed-off-by: = <=alex@mckpals.com>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jdinan** [comment]
Looks like the failure was caused by an upstream change in ISx:
```
[0003] WARN:  ../../src/symmetric_heap_c.c:137: shmem_internal_get_next
[0003]        Out of symmetric memory, heap size 537919488, overrun 1073745920
[0003]        Try increasing SHMEM_SYMMETRIC_SIZE
ISx v1.1
  Number of Keys per PE: 33554432
  Max Key Value: 32768
  Bucket Width: 8192
  Number of Iterations: 1
  Number of PEs: 4
  WEAK_ISOBUCKET Scaling!
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 12117 RUNNING AT testing-gce-83ffce2b-d481-4b37-b900-1ca14f3c4817
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by jdinan** [comment]
Thanks; this does look like it fixes a races with accesses to the ```dest``` array.  Might fix #286.

**Comment by davidozog** [comment]
Yes, this change fixes #286 as far as we can reproduce it.  (To reproduce, it helped to have more VM cores than physical cores.)

Not sure yet what's causing the ISx problems.

**Pull request merged**
