### PR TITLE
Fixes to the random STX allocator 

### PR DESCRIPTION
**Pull request by davidozog**
This makes the following changes to the random STX allocator:
* Call reentrant `rand_r` for thread safety (see #677).
* remove the "Fisher-Yates shuffle" scheme for fairness (it wasn't effective).
* Increase the "max reference" threshold on the default context by 1 for better balancing.
* Fill STX "slots" up to the threshold before picking another random STX.

### CODE REVIEW

**Comment by jdinan** [comment]
It looks like this random allocator may say "none available" (-1) for the given threshold, even when such an STX is available.  Is that ok, or should we force it to keep probing as long as such an STX is available?

**Comment by davidozog** [comment]
That's true.  I figure if random selection makes "sufficiently many" attempts, and it hasn't found such an STX, then it's just not worth the effort and best to commit to the next random selection (which is what happens with that -1).  I found that this relatively unfair randomness balances well enough (especially if the app has enough contexts relative to STXs).  

I'd be open to tracking whether such an STX is available if you'd like, but I'm not sure it's worth the extra code.  We could also increase the `shmem_transport_ofi_stx_max` heuristic to `2 * shmem_transport_ofi_stx_max` or something like that to reduce the chance this occurs.

**Comment by jdinan** [comment]
@davidozog Have you had a chance to review https://github.com/davidozog/sandia-shmem/pull/5?

**Comment by davidozog** [comment]
@jdinan Not yet, will review today.

**Pull request merged**
