### PR TITLE
signal wait until in shmem header to handle the compiler warning

### PR DESCRIPTION
**Pull request by wrrobin**
Related to #1039 

Signed-off-by: Md Rahman <md.rahman@intel.com>

### CODE REVIEW

**Comment by wrrobin** [comment]
@davidozog Could you please check if this is the right way to handle this?

**Comment by davidozog** [comment]
I think this function declaration is already included in `shmem_c_func.h4`.

See my comment in #1039.  I have a feeling it's just a "make clean" problem.

**Comment by wrrobin** [comment]
Oh.. it might be... I will check with a clean dir..

**Comment by wrrobin** [comment]
Yes.. `make clean` resolves this. Thanks. Closing this.

**Pull request closed without merging**
