### PR TITLE
Add bb performance counters

### PR DESCRIPTION
**Pull request by jdinan**
* Add bounce buffer performance counters
 * Add debug message to print diagnostic info upon context destruction
 * Fix type issue with SHMEM_CTX_* constants (int implicitly promoted to long)

### CODE REVIEW

**Comment by jdinan** [comment]
Sample output from `test/performance/shmem_perf_suite/shmem_bw_put_perf` (unidirectional bandwidth, measured with blocking puts):
```
[0000] DEBUG: ../../src/transport_ofi.c:1589: shmem_transport_ctx_destroy
[0000]        id = -1, options = 0x80000000, stx_idx = 0
[0000]        pending_put_cntr =    422546, completed_put_cntr =    422546
[0000]        pending_get_cntr =         0, completed_get_cntr =         0
[0000]        pending_bb_cntr  =    140801, completed_bb_cntr  =    140801
[0001] DEBUG: ../../src/transport_ofi.c:1589: shmem_transport_ctx_destroy
[0001]        id = -1, options = 0x80000000, stx_idx = 0
[0001]        pending_put_cntr =       146, completed_put_cntr =       146
[0001]        pending_get_cntr =         0, completed_get_cntr =         0
[0001]        pending_bb_cntr  =         1, completed_bb_cntr  =         1
```

**Comment by jdinan** [comment]
It's interesting that the target PE performed a bounce buffered put.  Wonder where that came from?

**Comment by wrrobin** [comment]
This PR looks good. I would review the changes. Regarding the bb counter values, its surprising. Immediately got the reason why this counter was needed :P Also, the put counter values are high compared to what I would expect. Is it reflecting only this BW test?

**Comment by jdinan** [comment]
It's the full application, including barriers, etc.  The put counter also includes non-fetching AMOs and the get counter includes fetching AMOs.

**Comment by wrrobin** [comment]
Thanks. The full application includes all the message sizes. In that case, the high put counter values are making sense.

**Comment by jdinan** [comment]
FYI, the +1 buffered put came from a call to `shmem_fcollect32` in `check_hostname_validation`.

**Pull request merged**
