### PR TITLE
OFI: account for count in recdbl switch

### PR DESCRIPTION
**Pull request by kseager**
Signed-off-by: kseager <kayla.seager@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
This fixes the bug, but would it be better to segment the message so we can still use the atomics?  Can we do the segmentation in the transport atomics?  I think we would have to extend these functions to take both a basic datatype length and a count so we segment on the right boundaries.

**Comment by jdinan** [comment]
Build error:
```
In file included from init.c:31:0:
shmem_collectives.h: In function ‘shmem_internal_op_to_all’:
shmem_collectives.h:149:13: error: too many arguments to function ‘shmem_transport_atomic_supported’
transport_portals4.h:1055:5: note: declared here
shmem_collectives.h:167:13: error: too many arguments to function ‘shmem_transport_atomic_supported’
transport_portals4.h:1055:5: note: declared here
shmem_collectives.h:178:13: error: too many arguments to function ‘shmem_transport_atomic_supported’
transport_portals4.h:1055:5: note: declared here
make[2]: *** [init.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from collectives.c:21:0:
shmem_collectives.h: In function ‘shmem_internal_op_to_all’:
shmem_collectives.h:149:13: error: too many arguments to function ‘shmem_transport_atomic_supported’
transport_portals4.h:1055:5: note: declared here
shmem_collectives.h:167:13: error: too many arguments to function ‘shmem_transport_atomic_supported’
transport_portals4.h:1055:5: note: declared here
shmem_collectives.h:178:13: error: too many arguments to function ‘shmem_transport_atomic_supported’
transport_portals4.h:1055:5: note: declared here
make[2]: *** [collectives.lo] Error 1
make[2]: Leaving directory `/home/travis/build/Sandia-OpenSHMEM/SOS/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/travis/build/Sandia-OpenSHMEM/SOS/src'
make: *** [all-recursive] Error 1
```

**Comment by kseager** [comment]
that is a good point about the segmentation....I'll put in something for that and you can let me know what you think

**Comment by kseager** [comment]
will have different pull request will resolution soon

**Pull request closed without merging**
