### PR TITLE
Exit with 0 for context creation failure in perf tests

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Comment by wrrobin** [comment]
@jdinan Should we go ahead and merge this to master?

**Comment by minsii** [comment]
Just checked `performance/shmem_perf_suite` is all green now ! Thanks !

**Comment by wrrobin** [comment]
Thanks @minsii for the update.

**Comment by jdinan** [comment]
@wrrobin go ahead and merge when ready.  Can you also apply the same changes to tests-sos and post a PR there so @minsii can pick it up in their testing?

**Comment by wrrobin** [comment]
Sure @jdinan. Will do.

**Pull request merged**
