### PR TITLE
SHMEM_CTX_INVALID for RMA, AMO, and context creation operations

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Comment by wrrobin** [comment]
@davidozog Good catch, Dave! Although, I see the clause in the spec is little different for fence and quiet. It says, no operation is performed if the `ctx` is `SHMEM_CTX_INVALID`. May be, we need to add a check to return immediately from the internal layer?

**Comment by davidozog** [comment]
@wrrobin Ah yes, very good call.  Looks like we might already have that, right?

In that case, we may not need the error check here...

**Comment by wrrobin** [comment]
Ah... yeah, just saw these changes already done in the internal layer, thanks!

**Comment by wrrobin** [comment]
@davidozog @rdesai16 Please check the latest commit in regards to #942. I am including these changes in this PR as well since they are very related.

**Comment by davidozog** [comment]
@wrrobin - I thought @jdinan had preferred to keep constants like `SHMEM_CTX_INVALID` and `SHMEM_TEAM_INVALID` outside the transport layers, but I can't remember the exact reason (perhaps it's organizational to keep the user-facing constants as high up the stack as possible).  Perhaps he can remind us?

Assuming that's ok, I think the changes from the last commit are good.

**Comment by jdinan** [comment]
At the transport layer, we tend to assume that it's a valid object creation request. It's generally good defensive programming to resolve these invalid/corner cases at the top level of the stack when possible. For example, the UCX code I posted also would need this fix if it's implemented at the transport level.

**Comment by wrrobin** [comment]
Thanks @davidozog. Yes, going ahead.

**Pull request merged**
