### PR TITLE
_Complex and _Noreturn

### LINKED ISSUE #465: OpenSHMEM 1.4 - change log #21 - replace complex with _Complex
Replace the `complex` macro in complex-typed reductions with the C99 (and later) type specifier `_Complex` to remove an implicit dependence on complex.h.

### PR DESCRIPTION
**Pull request by jdinan**
Closes #465 and #451

### CODE REVIEW

**Comment by davidozog** [comment]
Looks good!

**Comment by jdinan** [comment]
Appears to be a C++ compilation error in the profiling build:
```
make[1]: Entering directory `/home/travis/travis/src/tests-cray/sma2'
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_and_alltypes all_and_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_and_alltypes 2>&1
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_max_alltypes all_max_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_max_alltypes 2>&1
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_min_alltypes all_min_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_min_alltypes 2>&1
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_or_alltypes all_or_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_or_alltypes 2>&1
make[1]: [all_and_alltypes] Error 1 (ignored)
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_prod_alltypes all_prod_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_prod_alltypes 2>&1
make[1]: [all_max_alltypes] Error 1 (ignored)
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_sum_alltypes all_sum_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_sum_alltypes 2>&1
make[1]: [all_or_alltypes] Error 1 (ignored)
oshCC  -I/home/travis/travis/install/sandia-shmem-ofi/include/  -o /home/travis/travis/src/tests-cray/testbin/build/bin/sma2/all_xor_alltypes all_xor_alltypes.cpp   -L/home/travis/travis/install/sandia-shmem-ofi/lib64 -lsma  \
		> /home/travis/travis/src/tests-cray/testbin/build/out//sma2/all_xor_alltypes 2>&1
make[1]: [all_min_alltypes] Error 1 (ignored)
make[1]: [all_xor_alltypes] Error 1 (ignored)
make[1]: [all_prod_alltypes] Error 1 (ignored)
make[1]: [all_sum_alltypes] Error 1 (ignored)
make[1]: Leaving directory `/home/travis/travis/src/tests-cray/sma2'
```

**Comment by jdinan** [comment]
Profiling (pshmem) header generating was failing because ```shmem_c_func.m4``` was renamed to ```shmem_c_func.h4```.  Should be good to go now.

**Comment by jdinan** [comment]
Whoops

**Comment by davidozog** [comment]
Haha, aggressive git tidiness apparently has its costs...

It's interesting that the `--disable-cxx` row is failing due to (non-existent)  C++ Cray tests.  Looks like that script may need a check for `DISABLE_CXX` similar to the check for `SOS_DISABLE_FORTRAN`?

**Comment by jdinan** [comment]
It looks like the C++ compiler doesn't suport ```[[ noreturn]]```:
```
In file included from all_xor_alltypes.cpp:61:0:
/home/parallels/opt/sos-dev/include/mpp/shmem.h:112:27: error: expected unqualified-id before ‘[’ token
 SHMEM_FUNCTION_ATTRIBUTES [[ noreturn ]] void shmem_global_exit(int status);
                           ^
```

**Pull request merged**
