### PR TITLE
Add transport hook for spinlock body

### PR DESCRIPTION
**Pull request by jdinan**
OFI, check the CQ for errors while polling.

Signed-off-by: James Dinan <james.dinan@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
Feedback: @hppritcha @kseager

**Comment by kseager** [comment]
We would additionally need to add to ep_bind " | FI_RECV" to notify the provider we are now looking for inbound transfer cq error reporting.  As you mentioned earlier, since we are looking at inbound error checking we could add the ret + cq_error checking to received_cntr_wait , mirroring our local completion usage. 

In terms of the hard-polling pathway I would personally prefer someway to turn off this feature in order to preserve a pathway that doesn't call into the fabric.

**Comment by jdinan** [comment]
Oh ... FI_RECV may interfere with other code that assumes the CQ will only contain TX errors.  What about splitting the CQ endpoint into separate RX and TX endpoints?  RX goes into the AV and TX endpoints don't.  This seems like cleaner software engineering, but is it less efficient from an OFI perspective?

**Comment by jdinan** [comment]
So, we set ```FI_SELECTIVE_COMPLETION | FI_TRANSMIT``` on the counter-only TX EP to catch transmit errors.  This is interesting, given that we use RMA operations, which can never set ```FI_COMPLETE``` since there's no ```flags``` argument.  I guess I could use this same trick at the RX EP to set ```FI_SELECTIVE_COMPLETION | FI_RECV``` so that we collect RX errors.  Although, we already set ```FI_TRANSMIT``` when we bind this CQ to that EP.  Can I bind the same CQ again with different flags?

BTW, we seem to have lost the event slots tracking code from the Portals transport that ensure we have EQ space available before issuing ops that generate completion events (bounce buffered puts).  Should we log a ticket to fix this?

**Comment by kseager** [comment]
Good point about the API calls missing flags; MPI must've not run into this limitation 😉. For our purposes we don't need it for getting error events and want to suppress the successful completion anyways. 

Yes its the same trick on the RX side. Its seems like a waste to create two CQs per process just for splitting up the tx/rx error handling. In theory we check the queue right after the potentially erroneous operation so we should be getting the associated error event. The ret value of the operation should signal if there is an error to check. This code addition is the only time we are checking for an error via the cq vs. checking the return first.  

If its the same associate ep2eq then we should just OR on the extra flag like this:

     ret = fi_ep_bind(shmem_transport_ofi_cntr_epfd,
-                   &shmem_transport_ofi_put_nb_cqfd->fid, FI_SELECTIVE_COMPLETION | FI_TRANSMIT);
+                   &shmem_transport_ofi_put_nb_cqfd->fid, FI_SELECTIVE_COMPLETION | FI_TRANSMIT | FI_RECV );

Sure log and issue for the Portals code.

**Comment by jdinan** [comment]
PRK strikes again.  They changed the compiler flags upstream causing a build failure.  @davidozog will push a fix.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
okay try again
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by jdinan** [comment]
@hppritcha says that the GNI provider no longer needs this.  Closing.

**Pull request closed without merging**
