### PR TITLE
OFI: Fix missing fi_wait_obj attr on cntrs

### PR DESCRIPTION
**Pull request by jdinan**
Signed-off-by: James Dinan <james.dinan@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
@kseager @sayantansur - We always wait through the FI interface, so ```FI_WAIT_UNSPEC``` looks correct to me.

@kseager, you had wanted to also do some performance tuning of the wait behavior.  Do you want to log an issue for that, or propose a change?

**Comment by sayantansur** [comment]
Yea, this looks correct to me.

**Comment by kseager** [comment]
I guess given the urgency of this fix this works for now. I just tested it on gni and we are again compliant. thanks for this fix and yes lets file a performance tuning todo.

**Comment by jdinan** [comment]
Partially addresses #290

**Pull request merged**
