### PR TITLE
Manpages1.4

### PR DESCRIPTION
**Pull request by angelali4096**
Updated script to be compatible with version 1.4 of the specification. Changes include:
- Updated list of defined macros
- Supports bullet lists within manpages
- Creates manpage for every possible function (considering sizes and types)
- Tables no longer need to be in separate files

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by davidozog** [comment]
add to whitelist

**Comment by davidozog** [comment]
@hppritcha Will that "add to whitelist" get rid of this message on PRs from @angelali4096?

**Comment by jdinan** [comment]
Could you also create another PR to update the manpages in the SOS ```man/``` directory?

**Comment by angelali4096** [comment]
@jdinan 
I didn't do this beforehand because it would track more than 500 more files that could be automatically generated by the script. Also, if the script changes, some if not all the manpages will change. Is this what we want?

**Comment by jdinan** [comment]
Yeah, it's a lot of files, but we want to have them in the repository.  Otherwise, users would also need to have a copy of the spec to get a complete build.

**Comment by jdinan** [comment]
Looks good to me -- @davidozog ?

**Comment by jdinan** [comment]
IIUC, it requires a patched version of the OpenSHMEM 1.4-RC5.

**Comment by davidozog** [comment]
Cool, makes sense.  Just wondering if that's in a branch/tag somewhere for future reference.

**Comment by jdinan** [comment]
Works ok for me on the RC5 branch.

**Comment by davidozog** [comment]
Is that `jdinan:drafts/osh-1.4-rc5`?   I see `Error: shpdeallc.tex is not in the given directory`.

**Comment by jdinan** [comment]
Yeah, you also need this patch: https://github.com/jdinan/specification/pull/3

**Pull request merged**
