### PR TITLE
src: Update uthash.h to v2.3.0

### PR DESCRIPTION
**Pull request by philipmarshall21**
This PR updates **uthash.h** from v2.0.1 to v2.3.0

### CODE REVIEW

**Review by wrrobin — APPROVED** [review]
LGTM. 
@philipmarshall21 - Do you see the type inconsistencies that you found with the old version on the new one?

**Comment by philipmarshall21** [comment]
Yes, the new version still primarily uses **unsigned** (rather than **unsigned int**) and there is inconsistency in the file with respect to using **const unsigned char\*** in some places and in other places using **unsigned const char \***

**Review by davidozog — APPROVED** [review]
Looks good, thanks @philipmarshall21

**Comment by philipmarshall21** [comment]
> Looks good, thanks @philipmarshall21

You bet! If this branch is ok to be merged, the merge will need to be performed by an authorized user.

**Comment by davidozog** [comment]
> > Looks good, thanks @philipmarshall21
> 
> You bet! If this branch is ok to be merged, the merge will need to be performed by an authorized user.

@philipmarshall21 - I attempted to give you permission to merge.  Do you want to try on this PR?  This will likely be useful in the future...

**Comment by philipmarshall21** [comment]
> > > Looks good, thanks @philipmarshall21
> > 
> > 
> > You bet! If this branch is ok to be merged, the merge will need to be performed by an authorized user.
> 
> @philipmarshall21 - I attempted to give you permission to merge. Do you want to try on this PR? This will likely be useful in the future...

Interesting...on my end I still see that merging is blocked (with message "The base branch restricts merging to authorized users.").

**Pull request merged**
