### PR TITLE
Interface Selection

### PR DESCRIPTION
**Pull request by jdinan**
Add automatic interface selection using Hydra hostname variable and manual interface selection using SMA_OFI_IFACE environment variable.

### CODE REVIEW

**Comment by jdinan** [comment]
@kseager, @sayantansur, @jithinjosepkl -- Review would be much appreciated.

This is intended to fix issues with interface selection when we use the sockets provider with IPoIB.  The NULL address query to fi_getinfo has been causing the sockets provider to select the ethernet network rather than IPoIB, regardless of which hostnames are used during launch.

Questions:
 * Is the interface selection method I used reasonably portable (there's a different route which uses ioctl on a socket)?
 * Will the automatic hostname selection using the MPIR_... var mess up other providers (i.e. if we pass the hostname used to launch instead of NULL)?  I think it will, and am leaning toward removing it.  An alternative would be to push this hack (Hydra sets the env var in question) down into the sockets provider similarly to how it's consumed by the netmod MPICH.

**Comment by jithinjosepkl** [comment]
:+1:  You may also want to set FI_SOURCE as flags for getinfo(), since iface_addr/svc_name specify local source address.

FI_SOURCE
Indicates that the node and service parameters specify the local source address to associate with an endpoint. If specified, either the node and/or service parameter must be non-NULL.

**Comment by sayantansur** [comment]
I'm somewhat concerned that the usage of getifaddrs() builds in an assumption that interface name for every provider will be the same one as the "native" provider. There is no such requirement from OFI actually, each provider gets to define its own address structure.

**Comment by jdinan** [comment]
Closing.  This will be fixed in a future PR by searching the list of fabrics returned by fi_getinfo.

**Pull request closed without merging**
