### PR TITLE
Version and NEWS for 1.5.0 release

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Review by davidozog — COMMENTED** [review]
Thanks @wrrobin, looks great.

What do you think of possibly adding the following:
```
* Additional bugfixes - including profiling symbols for some team-based collectives, support for C99 compilation, and unit test failures when npes is 1.
```
(or some subset thereof)

**Comment by kholland-intel** [comment]
LGTM.

**Comment by wrrobin** [comment]
@davidozog Yes, I was thinking about those. Thought that we already mentioned about bug fixes in the 1.5.0rc1 release news. But, we can add as additional as well.

**Review by davidozog — APPROVED** [review]
Yup - I believe these bug fixes were after RC1, so probably worth mentioning.

It's probably best to merge this after merging PR #988 (Travis is awfully slow...).  Then I'll cut the release!

**Pull request merged**
