### PR TITLE
OFI:gni fixes for SOS to work with GNI provider

### PR DESCRIPTION
**Pull request by hppritcha**
modulo lack of support for certain AMO op sizes,
the gni provider can now be used with SOS if the
right config options are picked.  If not, SOS now gracefully
falls back to using the sockets provider on Cray
XC systems.

To work with GNI provider, the following configury options
are required:
--enable-hard-polling
--disable-mr-scalable

one will also need to set PMI_KVS_MAX_ENTRIES env. variable
to something like 1000000.

As of this commit, one also needs to if def out the loops
in ```atomic_limitations_check``` for GNI provider.

All check tests except for global_exit now run using GNI provider
using the following make check command:

make check TEST_RUNNER='srun -n 2 --exclusive'

@kseager 
@jdinan 

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
don't just close this pull request.  try to merge it with other work.
things seem to get missing otherwise.

**Comment by jdinan** [comment]
Sure -- I'll merge these changes into #168.  That contains your other changes already, in addition refactoring to clean up interfaces and better support the other builds.

**Comment by hppritcha** [comment]
@jdinan if you could do the merge via cherry-pick, it makes it much easier to track what gets in with your PR and what doesn't.  In general I find it hard to keep track of what changes if you pull something from another pr without cherry-pick.

**Comment by jdinan** [comment]
Yeah, sorry about that -- I'll see what I can do.  There are some changes that I had to fiddle with because of the refactoring that I mentioned, so it's not a clean cherry-pick.  I might be able to generate a patch and edit it to at least keep your commit message and ack you as the author...I'll look into it.

**Comment by jdinan** [comment]
@hppritcha - I cherry-picked these changes onto #168 and figured out how to hang on to your commit message this time.  Could you please review that branch (topic/transport-put-cntr) on jdinan and close this PR if all looks ok?  Thanks!

**Comment by hppritcha** [comment]
I'm a happy camper. Once #168 is in master please close the PR.  I'll try out gups at that point.

**Pull request closed without merging**
