### PR TITLE
Fix alltoall(s) tests to use unit stride w/ teams

### PR DESCRIPTION
**Pull request by davidozog**
This should fix issue #1035 

@kholland-intel - can you please check this resolves the failure you saw in these tests?

### CODE REVIEW

**Review by wrrobin — APPROVED** [review]

**Comment by davidozog** [comment]
@kholland-intel - I think this test always passed with 2 PEs because it only covered the following cases:
```
pe_start = 0, pe_stride = 0, pe_size = 2
pe_start = 0, pe_stride = 13, pe_size = 1
pe_start = 0, pe_stride = 1, pe_size = 1
pe_start = 0, pe_stride = 0, pe_size = 1
pe_start = 1, pe_stride = 0, pe_size = 1
pe_start = 1, pe_stride = 1, pe_size = 1
```
When `pe_stride` is 0, the `1 << 0` stride calculation did nothing.  For the other cases where `pe_stride` is not 0, there is only 1 PE.  That means only PE 0 is involved, so the stride calculation doesn't come into play (because `group_pe` is 0).

Anyway, that's a good question (asked offline ;).

**Review by kholland-intel — APPROVED** [review]
Thanks for this PR Dave, the changes look good to me and it appears to fix the failure. 

P.S. I am getting many warnings regarding invalid parameters to shmem_internal_team_split_strided function. Do you know if these warnings are related to this PR or maybe to #999?
```
$ oshrun -N 1 -n 8 ./alltoall_test
[0000] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0000]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0001] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0001]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0002] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0002]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0003] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0003]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0004] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0004]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0005] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0005]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0006] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0006]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0007] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0007]        Invalid <start, stride, size>: child <0, 0, 8>, parent <0, 1, 8>
[0000] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0000]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0001] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0001]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0002] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0002]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0002] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0002]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0003] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0003]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0003] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0003]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0004] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0004]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0004] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0004]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0005] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0005]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0005] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0005]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0006] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0006]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0006] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0006]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0007] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0007]        Invalid <start, stride, size>: child <0, 0, 7>, parent <0, 1, 8>
[0007] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0007]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0000] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0000]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
[0001] WARN:  ../../src/shmem_team.c:262: shmem_internal_team_split_strided
[0001]        Invalid <start, stride, size>: child <1, 0, 7>, parent <0, 1, 8>
A2A: pe_start = 0, pe_stride = 0, pe_size = 8
A2A: pe_start = 0, pe_stride = 13, pe_size = 1
A2A: pe_start = 0, pe_stride = 1, pe_size = 4
A2A: pe_start = 0, pe_stride = 0, pe_size = 7
A2A: pe_start = 1, pe_stride = 0, pe_size = 7
A2A: pe_start = 1, pe_stride = 1, pe_size = 4
```

**Comment by davidozog** [comment]
@kholland-intel - good question.  These warnings are valid - they're raised because the test is splitting with a stride of 0.  However, the original intent of the test was to split with (linear) size of 1 in (at least in this case).

So the underlying cause is that I forgot to update the `alltoall_test` and `alltoalls_test` function arguments in the tests after making the change in https://github.com/Sandia-OpenSHMEM/SOS/pull/1037/commits/4987ee030958fa8bdc4d074f67108860bd01eb52.

I just made that correction - can you please review that it makes sense?  @wrrobin may want to have a look too.

**Comment by kholland-intel** [comment]
That makes sense, thanks for clearing that up for me. These new changes look good to me.

**Pull request merged**
