### PR TITLE
Update dlmalloc from 2.8.4 to 2.8.6

### PR DESCRIPTION
**Pull request by jdinan**
Signed-off-by: James Dinan <james.dinan@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
Closes #275

**Comment by jdinan** [comment]
This patch syncs our ```malloc.c``` with the upstream version 2.8.6 from Doug Lea.

I ran a diff of the old code against dlmalloc 2.8.4 to make sure we didn't lose any local changes.  All of the local changes are carried over and are annotated with ```/* BEGIN SHMEM CHANGES */``` comments.

Github is being lame and not showing the changes, but there isn't really much to review here.  All I'm looking for is thumbsups that "hey, updating to 2.8.6 seems like a good idea."

**Comment by kseager** [comment]
it does seem like a good idea 👍

**Comment by jdinan** [comment]
Here is the relevant history:
```
History:
    v2.8.6 Wed Aug 29 06:57:58 2012  Doug Lea
      * fix bad comparison in dlposix_memalign
      * don't reuse adjusted asize in sys_alloc
      * add LOCK_AT_FORK -- thanks to Kirill Artamonov for the suggestion
      * reduce compiler warnings -- thanks to all who reported/suggested these

    v2.8.5 Sun May 22 10:26:02 2011  Doug Lea  (dl at gee)
      * Always perform unlink checks unless INSECURE
      * Add posix_memalign.
      * Improve realloc to expand in more cases; expose realloc_in_place.
        Thanks to Peter Buhr for the suggestion.
      * Add footprint_limit, inspect_all, bulk_free. Thanks
        to Barry Hayes and others for the suggestions.
      * Internal refactorings to avoid calls while holding locks
      * Use non-reentrant locks by default. Thanks to Roland McGrath
        for the suggestion.
      * Small fixes to mspace_destroy, reset_on_error.
      * Various configuration extensions/changes. Thanks
         to all who contributed these.

    V2.8.4a Thu Apr 28 14:39:43 2011 (dl at gee.cs.oswego.edu)
      * Update Creative Commons URL
```

**Pull request merged**
