### PR TITLE
Travis UCX Update

### PR DESCRIPTION
**Pull request by jdinan**
Supercedes #970

### CODE REVIEW

**Comment by jdinan** [comment]
Look out for:
 * bcast test failure: https://travis-ci.org/github/Sandia-OpenSHMEM/SOS/jobs/717927762
 * bigput timeout: https://travis-ci.org/github/Sandia-OpenSHMEM/SOS/jobs/717927761

**Comment by davidozog** [comment]
@jdinan - I should have mentioned that I tried updating to v1.8.1 and can reproduce the issue locally (see the new ticket #974) 

But yes, let's merge this update.  The issue seems less frequent on v1.8.1 (wishful thinking perhaps... ;).

**Comment by davidozog** [comment]
@jdinan - I think I'll merge this to include it in v1.5.0rc1 unless I hear otherwise...  trying to cut a release today.

**Comment by jdinan** [comment]
Go for it. :shipit:

**Pull request merged**
