### PR TITLE
Improvements to MR_SCALABLE support

### PR DESCRIPTION
**Pull request by jdinan**

### CODE REVIEW

**Comment by jdinan** [comment]
@sayantansur, this should address the MR_SCALABLE changes that you suggested.

**Comment by sayantansur** [comment]
Yay! This is the most responsive project on Github :100:

**Comment by jdinan** [comment]
Had to jiggle the handle a little, but this should be in good shape now.

**Comment by jdinan** [comment]
Yeah, there's progress in that direction on v1.3.0-dev, but still plenty more work to do.

**Pull request merged**
