### PR TITLE
Minor bug in travis script

### PR DESCRIPTION
**Pull request by wrrobin**

### CODE REVIEW

**Comment by wrrobin** [comment]
@davidozog @rdesai16 It seems like some of the shmemx -> shmem changes have been checked in to the master already? Or am I missing something? The build is failing with missing shmemx symbols.

**Comment by davidozog** [comment]
@wrrobin - I'm not seeing anything like that on my end.  Might want to try a fresh build on master and file and issue if it recurs.

**Comment by wrrobin** [comment]
@davidozog The travis build is failing. Please check [here](https://jenkins.open-mpi.org/jenkins/job/sos/971/).

**Comment by rdesai16** [comment]
That's strange! I am not seeing the changes checked into the master. I'll look into the Travis issue.

**Comment by davidozog** [comment]
Looks like Travis is fine (except for the known pmix/prrte issue) but Jenkins / LANL-CI is showing a strange error that I can't reproduce anywhere.

@hppritcha - Do you happen to see what could be causing this problem?  It appears that LANL-CI is not checking out the right revision or something very strange like that.

**Pull request merged**
