### PR TITLE
Generic C++ bindings for bitwise AMOs

### PR DESCRIPTION
**Pull request by jdinan**

### CODE REVIEW

**Comment by jdinan** [comment]
```
../../../test/unit/cxx_test_shmem_atomic_xor.cpp: In function ‘int main(int, char**)’:
../../../test/unit/cxx_test_shmem_atomic_xor.cpp:49:56: error: invalid conversion from ‘int32_t* {aka int*}’ to ‘unsigned int*’ [-fpermissive]
       shmem_atomic_xor(&remote, (TYPE)(1LLU << mype), i);               \
                                                        ^
../../../test/unit/cxx_test_shmem_atomic_xor.cpp:69:3: note: in expansion of macro ‘TEST_SHMEM_XOR’
   TEST_SHMEM_XOR(int32_t);
   ^
In file included from ../../../test/unit/cxx_test_shmem_atomic_xor.cpp:37:0:
../../mpp/shmem.h:1728:20: error:   initializing argument 1 of ‘void shmem_atomic_xor(unsigned int*, unsigned int, int)’ [-fpermissive]
 static inline void shmem_atomic_xor(unsigned int *dest, unsigned int value, int pe) {
                    ^
../../../test/unit/cxx_test_shmem_atomic_xor.cpp:49:56: error: call of overloaded ‘shmem_atomic_xor(int64_t*, int64_t, int&)’ is ambiguous
       shmem_atomic_xor(&remote, (TYPE)(1LLU << mype), i);               \
                                                        ^
../../../test/unit/cxx_test_shmem_atomic_xor.cpp:70:3: note: in expansion of macro ‘TEST_SHMEM_XOR’
   TEST_SHMEM_XOR(int64_t);
   ^
../../../test/unit/cxx_test_shmem_atomic_xor.cpp:49:56: note: candidates are:
       shmem_atomic_xor(&remote, (TYPE)(1LLU << mype), i);               \
                                                        ^
../../../test/unit/cxx_test_shmem_atomic_xor.cpp:70:3: note: in expansion of macro ‘TEST_SHMEM_XOR’
   TEST_SHMEM_XOR(int64_t);
   ^
In file included from ../../../test/unit/cxx_test_shmem_atomic_xor.cpp:37:0:
../../mpp/shmem.h:1731:20: note: void shmem_atomic_xor(long unsigned int*, long unsigned int, int) <near match>
 static inline void shmem_atomic_xor(unsigned long *dest, unsigned long value, int pe) {
                    ^
../../mpp/shmem.h:1731:20: note:   no known conversion for argument 1 from ‘int64_t* {aka long int*}’ to ‘long unsigned int*’
../../mpp/shmem.h:1734:20: note: void shmem_atomic_xor(long long unsigned int*, long long unsigned int, int) <near match>
 static inline void shmem_atomic_xor(unsigned long long *dest, unsigned long long value, int pe) {
                    ^
../../mpp/shmem.h:1734:20: note:   no known conversion for argument 1 from ‘int64_t* {aka long int*}’ to ‘long long unsigned int*’
make[3]: *** [cxx_test_shmem_atomic_xor.o] Error 1
make[3]: Leaving directory `/home/travis/build/Sandia-OpenSHMEM/SOS/no-transport-build/test/unit'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/travis/build/Sandia-OpenSHMEM/SOS/no-transport-build/test/unit'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/Sandia-OpenSHMEM/SOS/no-transport-build/test'
make: *** [check-recursive] Error 1
The command "make $TRAVIS_PAR_MAKE check TESTS=" exited with 2.
```

**Comment by jdinan** [comment]
Travis is using gcc 4.8.4.  This could be a bug in that version of the compiler.  Can't reproduce it locally with clang, gcc 6.4 or gcc 7.2.

**Comment by davidozog** [comment]
I also cannot reproduce in 5.4.0, but can reproduce in 4.8.2

**Comment by jdinan** [comment]
Ok, looks like an issue with the implementation of ```_Generic``` in gcc 4.8 (which is currently tied to C++ bindings generation).

**Comment by jdinan** [comment]
Woah, somehow this was closed without being merged (looks like my fault).

**Pull request closed without merging**
