### PR TITLE
Fix for flags in fi_writemsg APIs

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
@shefty Do we need to also make the same change to `fi_atomicmsg` API calls (we pass only `FI_INJECT` flag currently)?  The completion models aren't listed under flags for the atomic-msg APIs.

**Comment by shefty** [comment]
@jdinan - I think that's just an oversight in the man pages.  FI_DELIVERY_COMPLETE is implied for any 'fetch' atomic operation.

**Comment by wrrobin** [comment]
@shefty Just to understand, so, we will not need to explicitly pass `FI_DELIVERY_COMPLETE` as an argument for `fi_fetch_atomicmsg`, but need to do so for `fi_atomicmsg` and `fi_compare_atomic_msg`?

**Comment by shefty** [comment]
fi_fetch_atomicmsg and fi_compare_atomicmsg can both return results back to the caller.  If results are being returned (i.e. fetched) then FI_DELIVERY_COMPLETE is implied, though it's harmless to request it.  You would need it for fi_atomicmsg.

**Comment by wrrobin** [comment]
@jdinan Please re-review the new changes. Thanks.

**Comment by jdinan** [comment]
Thanks, @wrrobin and @shefty!

**Pull request merged**
