### PR TITLE
Fix inline assembly for SPINLOCK_BODY for aarch64.

### PR DESCRIPTION
**Pull request by srki**
Signed-off-by: Srđan Milaković <sm108@rice.edu>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by hppritcha** [comment]
okay to test

**Comment by hppritcha** [comment]
@jdinan Srdjan is one of my interns from Rice.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Pull request merged**
