### PR TITLE
Manpages for OpenSHMEM v1.5

### PR DESCRIPTION
**Pull request by davidozog**
I ran `scripts/generate_manpages.py` with some slight modifications to produce a nice starting point for OpenSHMEM v1.5 manpages (thanks @angelali4096!).  The script has some issues with the new tables and various latex section references, so I manually cleaned those up as best I could.  I have a feeling this might become intractable for v1.6 unless we fix the script... but we'll see :)

@wrrobin - do you think we should include this in SOS v1.5.0?  There're a lot of new files... but most are one-liners.

Also flagging @jdinan in case this is of interest.

### CODE REVIEW

**Comment by angelali4096** [comment]
Can you include a screenshot of the manpage for `shmem_reductions`?

**Comment by davidozog** [comment]
Sure - I definitely cleaned up `shmem_reductions.3` quite a bit...
Screen Shot 2020-10-29 at 12 58 22 PM
Screen Shot 2020-10-29 at 12 58 39 PM
Screen Shot 2020-10-29 at 12 58 53 PM

**Comment by angelali4096** [comment]
Oh good god. `reduce` is the worst one. (You missed the C[99] and C[11] in this one)

**Comment by davidozog** [comment]
@angelali4096 Haha, yeah... `reduce` is a little messed up.  But over 100 routines point to it, so it's a good one to clean up manually ;)

Oops - the screenshots do show C[99] and C[11], but I was looking at them from the previous commit.  It should be fixed in the current commit.

**Comment by wrrobin** [comment]
@davidozog This is a big set of changes but not critical. So, we can see if we can go over all the changes before 1.5.0 and approve. Otherwise, we can defer it for next time.

**Comment by kholland-intel** [comment]
@davidozog I went through all of the manpages and i only noticed 3 minor formatting issues. I'm not exactly sure if they are a direct result of your commits or how I should point you to them so I'll just list them here :)

1. In the manpages for "shmem_alltoall" I noticed a very small issue where the word "lth" is omitted from the following phrase in the API Description:

> Given a PE i that is the kth PE participating in the operation and a PE j that is the lth PE participating in the operation,

2. In the manpages for "shmem_team_split_2d" there are formatting issues under the "Return Values" and "API Notes" portions of the entry. I am assuming that there is some trouble in interpreting the table that is located in the Notes section of this entry in the 1.5 Spec.
3. In the manpages for "shmem_team_split_strided" there are some formatting issues under the "API Notes" section of the entry, around the following phrase:

> See the description of team handles and predefined teams in Section 9.4 for more information about team
handle semantics and usage.

Other than these small issues everything looks good to me!

**Comment by davidozog** [comment]
Thanks @kholland-intel - I see these issues and at least a few others in `shmem_team_split_strided`...

I think it's ok to fix these few issues manually.  We now have a record of where the problems are in case anybody has time to fix the Python script in the future.  Does that sound good?  If so, I'll do this asap - but that'll probably be next week.

**Comment by davidozog** [comment]
@kholland-intel - I made a pass through the noted manpages, fixing the issues you found and a few more I came across.  These changes are ready for a review - thanks!

**Comment by kholland-intel** [comment]
@davidozog LGTM

**Comment by davidozog** [comment]
Thanks @kholland-intel!

If you think it's ready to merge, please give it an "approved" review.  (i.e. using the "Review changes" button in the "Files changed" tab).

**Review by kholland-intel — APPROVED** [review]
This looks ready to merge.

**Pull request merged**
