### PR TITLE
Fix collect bug, improve bandwidth efficiency, and add unit test

### PR DESCRIPTION
**Pull request by jdinan**

### CODE REVIEW

**Comment by jdinan** [comment]
@kseager

**Comment by kseager** [comment]
Could you do a quick sanity check on gni? I highly doubt there will be an issue but its good to verify.  

Otherwise this looks clean to me. Additionally, I double checked the bug find/resolution and that also checks out. So from my POV this looks great. Good job, so glad you found this! 👍

**Comment by jdinan** [comment]
There shouldn't be any change here that impacts the GNI provider build and it's pretty time consuming to run tests there.  Can we check that platform periodically, rather than per PR?  (it would be so nice if we had nightlies running on that platform...)

**Comment by kseager** [comment]
ok fair enough

**Pull request merged**
