### PR TITLE
Add github stats logging script

### PR DESCRIPTION
**Pull request by jdinan**
* Move Travis scripts to scripts/travis
* Add copyright to generate_manpages and add .py extension
* Add github statistics logger to scripts

### CODE REVIEW

**Comment by jdinan** [comment]
@AMcKinley15 Could you do a detailed review of the new script?
@davidozog Could you sanity check the other changes?
@wrrobin I moved the Travis scripts, does this affect the other testing setup?

**Comment by davidozog** [comment]
@jdinan: Yup, moving the Travis scripts is definitely sane.  Consider it approved from me.  Like you mentioned, my only concern would be the effects on @wrrobin's end.

**Comment by wrrobin** [comment]
@jdinan It would require a small set of changes in the Jenkins setup, which I will handle. I do not assume any major hiccup. The changes look good to me as well.

**Comment by AMcKinley15** [comment]
@jdinan The script looks good to me.

**Pull request merged**
