### PR TITLE
Update RPM Build

### PR DESCRIPTION
**Pull request by jdinan**
* Update RPM build to cleanly uninstall when `%{_prefix} != /usr`
* Installs docs (README, LICENSE, etc.) under /usr/share as part of standard installation (simplifies RPM)
* Rename packaging from sos to sandia-openshmem to avoid name conflict with https://github.com/sosreport/sos

### CODE REVIEW

**Comment by jdinan** [comment]
@matcabral Could you please cherry pick and test 2fb8416 and fd9ef93.

**Comment by matcabral** [comment]
Cherry-picked both commits and can confirm that during uninstall now the rpm is correctly removing the install path when a custom _prefix is used.  thanks,

**Comment by jdinan** [comment]
@wrrobin This is ready for review.  One of the Travis failures was a false positive.  The other occurred because the testing ran too long because I added testing the prefixed RPM build to Travis.  I restarted both.  If it continues to take too long, I'll look into how to rearrange things so it doesn't timeout.

**Comment by jdinan** [comment]
You can safely ignore the Travis failure; they are unrelated to this PR.  I messed up and pushed this branch to the main repository instead of my fork, so the icc tests are being run (normally the icc tests are skipped).  Looks like the icc timeout issue with the Mellanox tests has been there a while.

**Comment by wrrobin** [comment]
@jdinan yes, I have seen the icc hang issue earlier with other PRs

**Pull request merged**
