### PR TITLE
Fix global_exit seg fault when no backtracing method is available.

### PR DESCRIPTION
**Pull request by davidozog**
This is a quick fix for #866.

### CODE REVIEW

**Comment by wrrobin** [comment]
@davidozog Thanks for the PR. Although this does fix the problem, I am thinking to assign a default value other than "" to `BACKTRACE`. If we want to keep it disabled by default, then may be we can use a default value of "disabled" or "N/A". We have maintained a default value for all other string type variables. This way, it will be consistent as well. 

@jdinan @davidozog Your thoughts?

**Comment by jdinan** [comment]
Hang on, something is wrong.  The default for this env var is `""`, so `shmem_internal_getenv_string` should assign a reference to the empty string (i.e. not `NULL`).  Is the env var being touched prior to the call to `shmem_internal_parse_env`?

**Comment by jdinan** [comment]
@wrrobin `SHMEM_BACKTRACE` appears to be the only string env var where the default value is the empty string.  A better default is not a bad idea, but there is a non-NULL default value.

**Comment by davidozog** [comment]
Yeah,  I have no idea why `method` is `NULL` - it should be an empty string.

It looks like this might be unique to my WIP branch.  On my end, the env var is read within `shmem_global_exit`, and long after `shmem_init`.  But, I just checked the master branch and see that `method` is `\0`, so perhaps we can close this PR...

**Comment by davidozog** [comment]
I found my problem.  I had removed `#include "config.h"` from `shmem_env.h` for no good reason (I saw it was in `shmem_env.c`, so I flippantly removed it from the header...)  Sorry for the false alarm.  It's kinda hard to diagnose these issues caused by not including `config.h`...

**Comment by wrrobin** [comment]
Thanks @jdinan @davidozog. Good to know that it got fixed.

**Pull request closed without merging**
