### PR TITLE
Optional Manpages

### PR DESCRIPTION
**Pull request by wrrobin**
Making manpages optional

### CODE REVIEW

**Comment by davidozog** [comment]
@wrrobin - I have a patch to fix the RPM generation when manpages are disabled.  Do you mind if I push that here so you can review?  (I was able to force push a rebase of this branch onto `main`, so it should work).

**Review by davidozog — APPROVED** [review]

**Comment by wrrobin** [comment]
The latest commit changes look good to me, Dave.

**Comment by davidozog** [comment]
Thanks @wrrobin.

This one is ready for review @kholland-intel

**Review by kholland-intel — APPROVED** [review]
Looks good!

**Pull request merged**
