### PR TITLE
(v1.4.x) cherry-pick features/fixes ahead of v1.4.5

### PR DESCRIPTION
**Pull request by davidozog**
I went ahead and created a `v1.4.x` branch on SOS that is synced with the `v1.4.5` tag.

This PR cherry-picks several commits from the master branch to include in `v1.4.x` to fix some bugs and have a useful Travis script.  Here's a short list of what's included:

* 8de8a785075b3cf5498c8753d98814506ce5e396 to allow higher thread levels in the tests and adds to `v1.4.x`. 
* All commits from PR #968 (teams bug fixes)
* ea3ea06749af57fb12fb48ddac23eaf6ca01244f to fix XPMEM testing in Travis
* A manual merge of the updates from PR #966  (primarily to update PMIx support in Travis)

I'll also add the shmem_perf_suite trial multiplier in PR #988 (and sync with https://github.com/openshmem-org/tests-sos) to `v1.4.x` after it's approved/merged into master.

All should feel free to request other features/bug fixes for `v1.4.x`.

### CODE REVIEW

**Comment by davidozog** [comment]
@wrrobin, @kholland-intel - This is ready for a review.

Keep in mind everything here has already been reviewed in the context of the SOS master branch (except the NEWS file and the v1.4.x autoconf version number).

I will also carry the relevant state from this branch over to a new `v1.4.x` branch on the `tests-sos` repo.

**Comment by davidozog** [comment]
Whoops, sorry @wrrobin / @kholland-intel - I still need to bring in the changes from #988, _then_ this will be ready for review... doing that now.

**Comment by davidozog** [comment]
Ok, I cherry picked those changes - now it's ready ;)

**Review by wrrobin — APPROVED** [review]
Looks good. Hope the tests pass. :)

**Pull request merged**
