### PR TITLE
Updates for v1.3.3rc1 release

### PR DESCRIPTION
**Pull request by jdinan**
* Update NEWS
* Bump version to v1.3.3rc1
* Last minute fixes to memory management API

### CODE REVIEW

**Comment by jdinan** [comment]
@ireed Could you check the realloc/align/free fixes against the Mellanox tests?

**Comment by davidozog** [comment]
`shmemalign` unit tests are failing though...

**Comment by jdinan** [comment]
Should be fixed with f1fb86c.

**Comment by jdinan** [comment]
Cray tests require implementation to round up to nearest power of two.  Latest patch should fix this.

**Comment by ireed** [comment]
If shmem_align is a fancy wrapper for memalign then that may cause issues with the mellanox tests. memalign(0,100) and memalign(3,100) return valid pointers on my system, thus failing the tests. But, posix_memalign() does work.

**Comment by jdinan** [comment]
We will return NULL in both those cases since the alignment is less than size(void*) (which is 8).

**Comment by ireed** [comment]
(update) The merged code is not passing the malloc tests, BUT it works if i manually write the test code in a new program (it fails if i do this without the merge).

**Comment by ireed** [comment]
Passes the original failing malloc tests, but fails a different test now. 
`    /* test that we get desired alignments */
    for (align = 1; align <= 4096; align *= 2)
    {
       p = shmem_align(align, 37);
       if (!p)   log_debug(OSH_TC, "failed to alloc with align = %d\n", align);

       if ((unsigned long)p & (align-1))     log_debug(OSH_TC, "failed to alloc with align = %d\n", align);
       shmem_free(p);
    }
`

(fails when align is 1, 2, and 4; passes in subsequent iterations)
This test passed before the merge. 
My guess is that the new cap on 8byte alignment affected this test.

**Comment by jdinan** [comment]
Ok, we can back out that change.  Since the spec doesn't place any restrictions on alignment, I suppose that we shouldn't either.

**Pull request merged**
