### PR TITLE
Disabling PMIx tests on Travis temporarily

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
What is the issue with PMIx? Could this be fixed by updating Travis to use the last known good version of PMIx/PRRTE rather than disabling testing?

**Comment by davidozog** [comment]
@jdinan - There are a lot of details, but in short, there is a build issue with prrte `v1.0.0` on Ubuntu 18.04, (so for that a a few other pmix-compatibility reasons) we need to update prrte to master (there is no recent prrte tag and likely will not be for a little while).  The other issue is with the `libev-dev` apt package(s) - they won't work with prrte master at the moment, so we'd need to move back to libevent.

While writing an issue describing this yesterday I stumbled upon a configuration that works in Ubuntu 18.04 - prrte/pmix masters, both linked with libevent 2.1.10.  I think I'll push that through Travis as one last ditch effort, but if this doesn't work out we might need to cut our losses and fix it later.  We've spent too much time on this already - it's a bit of a whack-a-mole problem.

**Comment by davidozog** [comment]
I drafted an alternative to disabling all PRRTE/PMIx rows in #966. 

There are trade-offs, and I'm open to either approach.  Any preferences from @wrrobin @jdinan @rdesai16 @rhc54 ?

**Comment by wrrobin** [comment]
Workaround by #966

**Pull request closed without merging**
