### PR TITLE
jenkins test - don't merge

### PR DESCRIPTION
**Pull request by hppritcha**
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
okay now try again
bot:lanl:retest

**Comment by hppritcha** [comment]
LANL CI working for now.  I'll enhance it to actually run the unit tests later.
@jdinan @kseager

**Comment by jdinan** [comment]
Woo hoo!!  :)

**Pull request closed without merging**
