### PR TITLE
Travis: check for missing pshmem symbols

### PR DESCRIPTION
**Pull request by jdinan**
Bit of a hack, but this should catch it if we are missing any pshmem functions in the future.

### CODE REVIEW

**Comment by jdinan** [comment]
@hppritcha Looks like LANL-CI is having trouble cloning the SOS repository.

**Comment by jdinan** [comment]
@davidozog @wrrobin What do you think of this PR?

**Comment by wrrobin** [comment]
Looks good to me @jdinan

**Comment by davidozog** [comment]
It may be my fault, but when I try this on my teams branch, I get a bunch of `shmem_op_*` symbols from `shmem_internal_op.h` that have no pshmem definitions.  So should we add `shmem_op` to this grep filter?

**Comment by jdinan** [comment]
@davidozog Those op functions should be static inline, so I wouldn't expect to see them in the built library.  We might also want to change the name to `shmem_internal_op*` to follow our naming convention.

**Comment by jdinan** [comment]
Scratch that, I see the op functions showing up, too ...

**Comment by jdinan** [comment]
It's a bit longer, but here's one solution that uses Perl instead of `sort` and `uniq`:
`nm src/.libs/libsma.so | grep shmem_ | grep -v -e shmem_internal -e shmem_transport -e shmem_free_list -e shmem_runtime -e shmem_util -e shmem_spinlock -e shmem_op -e '_$' | sed -e 's/^.* . //' | perl -e 'while (<>) { if (/^p/) { $h{substr $_,1} -= 1; } else { $h{$_} += 1 } } for $k (keys %h) { if ($h{$k}) { print $k; } }'`

**Comment by jdinan** [comment]
Here's an explanation for the Perl script:
```
// Read a line of input into $_
while (<>) {
  // if the string begins with p, subtract one from the corresponding
  // entry in the hash (with the leading p removed by substr)
  if (/^p/) { $h{substr $_,1} -= 1; }
  // otherwise increment the entry in the hash
  else { $h{$_} += 1 }
}

// Iterate over entries in the hash and print any that are nonzero
for $k (keys %h) { if ($h{$k}) { print $k; ++$f; } }
die "Missing profiling symbols" unless $f == 0;
```

**Pull request merged**
