### PR TITLE
Fix/test corner cases in collectives

### LINKED ISSUE #144: Collectives with length == 0
### Issue

Collectives with `length` or `nelems` of `0` are not tested and may be buggy.
### Solution

Update unit tests or add new ones to cover this case.

Alltoall and alltoalls already test this and the implementation handles it as a special case.

### PR DESCRIPTION
**Pull request by jdinan**
* nop test: test that src/dest buffers are ignored when nelems is zero
* self test: test operation when active set contains only the calling PE

Closes #144

### CODE REVIEW

**Comment by hppritcha** [comment]
maintenance was going on at NERSC.  retrying.
bot:lanl:retest

**Comment by jdinan** [comment]
🙁 
```
checking if user requested PMI support... yes
checking for pmi.h in /opt/cray/pmi/default/include... not found
checking for pmi.h in /opt/cray/pmi/default/include/slurm... not found
checking for libpmi in /opt/cray/pmi/default... not found
checking for libpmi in /opt/cray/pmi/default/lib64... not found
checking for libpmi in /opt/cray/pmi/default/lib... not found
checking for pmi2.h in /opt/cray/pmi/default/include... not found
checking for pmi2.h in /opt/cray/pmi/default/include/slurm... not found
checking for libpmi2 in /opt/cray/pmi/default... not found
checking for libpmi2 in /opt/cray/pmi/default/lib64... not found
checking for libpmi2 in /opt/cray/pmi/default/lib... not found
checking for pmi.h in /opt/cray/pmi/default/include... not found
checking for pmi.h in /opt/cray/pmi/default/include/slurm... not found
checking for libpmi in /opt/cray/pmi/default... not found
checking for libpmi in /opt/cray/pmi/default/lib64... not found
checking for libpmi in /opt/cray/pmi/default/lib... not found
checking can PMI support be built... no
configure: WARNING: PMI support requested (via --with-pmi) but neither pmi.h
configure: WARNING: nor pmi2.h were found under locations:
configure: WARNING:     /opt/cray/pmi/default
configure: WARNING:     /opt/cray/pmi/default/slurm
configure: WARNING: Specified path: /opt/cray/pmi/default
configure: WARNING: OR neither libpmi nor libpmi2 were found under:
configure: WARNING:     /opt/cray/pmi/default/lib
configure: WARNING:     /opt/cray/pmi/default/lib64
configure: WARNING: Specified path: 
configure: error: Aborting
```

**Comment by agrippa** [comment]
I ran into this recently, they changed the paths to PMI. I've been using /opt/cray/pe/pmi/5.0.11.

**Comment by hppritcha** [comment]
hey, what's the deal with NERSC?  Looks like they upgraded the system and forgot to install some Cray software.  I don't see how the craypich is currently working on that system.  I filed a ticket with NERSC marking importance high.

**Comment by hppritcha** [comment]
ufff... 
okay, I'll see about adding a pkgconfig based option to the SOS configury.

**Comment by hppritcha** [comment]
hmm... test temporary fix for jenkins CI wrt Cray PMI move.
bot:lanl:retest

**Pull request merged**
